image: $CI_REGISTRY_IMAGE:latest

stages:
  - build-image
  - release-image
  - compile
  - test

variables:
  GIT_SSL_NO_VERIFY: "1"
  TEST_IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  RELEASE_IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

before_script:
  - export PATH=$PATH:$HOME/iverilog/bin

build-image:
   image: docker:latest
   stage: build-image
   script:
     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
     - docker build --pull -t $TEST_IMAGE_TAG .
     - docker push $TEST_IMAGE_TAG

release-image:
  image: docker:latest
  stage: release-image
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $TEST_IMAGE_TAG
    - docker tag $TEST_IMAGE_TAG $RELEASE_IMAGE_TAG
    - docker push $RELEASE_IMAGE_TAG

compile:
  stage: compile
  script:
    - mkdir -p build
    - cd build
    - rm -rf *
    - cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/ -DBUILD_CLANG=ON
    - cmake --build . --target all --clean-first -- -j2  CCACHE_DIR=$(pwd)/../ccache
  cache:
      untracked: true
      paths:
        - ccache/
        - build/

test:
  stage: test
  script:
    - cd build
    - ctest -j2
    - cd ..
  cache:
      untracked: true
      paths:
        - ccache/
        - build/