include(CheckCXXCompilerFlag)
function(enable_cxx_compiler_flag_if_supported flag build_type)
    string(FIND "${CMAKE_CXX_FLAGS}" "${flag}" flag_already_set)
    if(flag_already_set EQUAL -1)
        check_cxx_compiler_flag("${flag}" flag_supported)
        if(flag_supported)
            set(CMAKE_CXX_FLAGS${build_type} "${CMAKE_CXX_FLAGS${build_type}} ${flag}" PARENT_SCOPE)
        endif()
    endif()
endfunction()

include(CheckCCompilerFlag)
function(enable_c_compiler_flag_if_supported flag build_type)
    string(FIND "${CMAKE_C_FLAGS}" "${flag}" flag_already_set)
    if(flag_already_set EQUAL -1)
        check_cxx_compiler_flag("${flag}" flag_supported)
        if(flag_supported)
            set(CMAKE_C_FLAGS${build_type} "${CMAKE_C_FLAGS${build_type}} ${flag}" PARENT_SCOPE)
        endif()
    endif()
endfunction()